server {
    listen 80;
    server_name localhost;

    # Diz para o Nginx onde estão os arquivos do seu site
    root /usr/share/nginx/html;
    index index.html;

    location / {
        # A MÁGICA ACONTECE AQUI:
        # 1. Tenta achar o arquivo exato ($uri)
        # 2. Se não achar, tenta achar uma pasta ($uri/)
        # 3. Se não achar nada, devolve o index.html (deixando o React cuidar da rota)
        try_files $uri $uri/ /index.html;
    }

    # Opcional: Configuração para não guardar cache de arquivos cruciais
    location ~* \.(?:manifest|appcache|html?|xml|json)$ {
        expires -1;
    }

    # Opcional: Guarda cache de imagens e estilos por 1 ano para o site abrir mais rápido
    location ~* \.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc|css|js)$ {
        expires 1y;
        access_log off;
        add_header Cache-Control "public";
    }
}