server {
    # MUDANÇA: Usamos 8080 pois não tem permissão para a porta 80
    listen 8080;
    server_name localhost;

    # Onde os arquivos do React foram copiados no Dockerfile
    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Essencial para React Router (Single Page Application)
        try_files $uri $uri/ /index.html;
    }

    # Configuração de Cache (Excelente para performance!)
    location ~* \.(?:manifest|appcache|html?|xml|json)$ {
        expires -1;
    }

    location ~* \.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc|css|js)$ {
        expires 1y;
        access_log off;
        add_header Cache-Control "public";
    }

    # Adicionado para evitar erro de logs se o Nginx tentar escrever sem permissão
    error_log /var/log/nginx/error.log warn;
    access_log /var/log/nginx/access.log;
}